---
run:
  deadline: 10m

linters-settings:
  errcheck:
    ignore: fmt:[FS]?[Pp]rint*,github.com/spf13/cobra:Mark*

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  enable:
    - whitespace
    - misspell
    - goimports
