---
project_name: kickoff
builds:
  - main: ./cmd/kickoff
    binary: kickoff
    ldflags:
      - -s -w
        -X github.com/martinohmann/kickoff/internal/version.gitVersion=v{{.Version}}
        -X github.com/martinohmann/kickoff/internal/version.gitCommit={{.FullCommit}}
        -X github.com/martinohmann/kickoff/internal/version.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    files:
      - none*
    replacements:
      linux: Linux
      darwin: Darwin
      386: i386
      amd64: x86_64
release:
  github:
    owner: martinohmann
    name: kickoff
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
