---
language: go
sudo: false
go:
  - "1.13"
  - tip
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script:
  - make coverage
  - make lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
