---
## Skeleton description
#
# Add some useful hints for the usage of this skeleton.
description: |
  Some example skeleton

## Custom configuration values
#
# Custom config is made available in *.skel template under {{ .Values }}. E.g.
# the example below can be used in templates as
# {{ .Values.travis.publishCodeCov }}.
values:
  travis:
    publishCodeCov: false
