---
project:
  host: github.com
  owner: martinohmann
  email: ""
  license: mit
  gitignore: go,hugo
repositories:
  kickoff-skeletons: https://github.com/martinohmann/kickoff-skeletons
values:
  travis:
    publishCodeCov: true
